### ISSUE TITLE
Better recommended formatting for array of objects?

### ISSUE THREAD

**Issue by tmccombs** [gura-conf/gura#9]
Consider this modified version of the example for arrays from https://gura.netlify.app/:

```
tango_singers: [
    name: "Carlos"
    surname: "Gardel"
    year_of_birth: 1890,
    name: "Aníbal"
    surname: "Troilo"
    year_of_birth: 1914
]
```

it contains two objects, but the comma is very easy to miss.  If a comma is the only only way to split elements of an array, it might be better to recommend formatting arrays of objects like:

```
tango_singers: [
    name: "Carlos"
    surname: "Gardel"
    year_of_birth: 1890
    ,
    name: "Aníbal"
    surname: "Troilo"
    year_of_birth: 1914
]
```

**Comment by Genarito** [comment]
Hi @tmccombs!

I agree with your comment. I sent the link to this issue to [the Discord server](https://discord.gg/Qs5AXPQpKd) to see if any user has any comments about it. As soon as I receive a reply or the end of the day arrives I will apply the changes to the page!

Thanks and greetings!

**Comment by Genarito** [comment]
Hi!

We've updated the site to add a suggestion about newlines to improve readability in the [Array section](https://gura.netlify.app/docs/spec#array). In Discord we came to the conclusion that it is more desirable to add the line after the comma and not the comma on a new line as was proposed. Example from the new docs:

```yaml
# It is valid but a little hard to read
singers: [
    name: "Andrea"
    surname: "Bocelli"
    gender: "Opera",
    name: "Jimi"
    surname: "Hendrix"
    gender: "Rock"
]

# Much better!
singers: [
    name: "Andrea"
    surname: "Bocelli"
    gender: "Opera",

    name: "Jimi"
    surname: "Hendrix"
    gender: "Rock"
]
```

Thanks for improving Gura!
